import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ButtonSidebar from "./components/Buttons";
import { LayoutGrid } from "lucide-react";
import ButtonsSidebar from "./Buttons";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FineBank | App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
