import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ButtonSidebar from "./components/Buttons";
import { LayoutGrid } from "lucide-react";
import ButtonsSidebar from "./Buttons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FineBank | App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="flex flex-col items-center h-screen w-60 bg-zinc-900 text-zinc-200">
            <div className="mt-8 text-xl">
              <span className="font-bold">FINE</span>bank
              <span className="font-bold">.IO</span>
            </div>
            <div className="flex flex-col gap-4 mt-4">
              <ButtonsSidebar />
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
